---
apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-configmap
  namespace: n8n-1 
  labels:
    app: n8n
    component: configmap
data:
  NODE_ENV: "production"
  GENERIC_TIMEZONE: "America/Sao_Paulo"
  WEBHOOK_TUNNEL_URL: "http://n8n.mvpos.app.br/"
  N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: true
  N8N_RUNNERS_ENABLED: true
  N8N_LISTEN_ADDRESS: "0.0.0.0"
  N8N_METRICS: true
  N8N_PAYLOAD_SIZE_MAX: 16
  N8N_DIAGNOSTICS_ENABLED: false
  N8N_ENCRYPTION_KEY: "jHuzVEWztfHRIqu9q6"
  # Configura o nível de log do N8N
  N8N_LOG_LEVEL: "info"
  # Database configurations
  DB_TYPE: "postgresdb"
  DB_POSTGRESDB_USER: "n8n"
  DB_POSTGRESDB_DATABASE: "n8n"
  DB_POSTGRESDB_HOST: "postgres-service"
  DB_POSTGRESDB_PORT: "5432"
  # Turn on basic auth
  N8N_BASIC_AUTH_ACTIVE: "true"
  N8N_BASIC_AUTH_USER: "n8n"