apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: n8n-data
  name: n8n-data
  namespace: n8n
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi