apiVersion: v1
kind: ConfigMap
metadata:
  namespace: n8n
  name: n8n-config
data:
  NODE_ENV: "production"
  N8N_METRICS: "true"
  N8N_DIAGNOSTICS_ENABLED: "false"
  N8N_PAYLOAD_SIZE_MAX: "16"
  N8N_LOG_LEVEL: "info"
  GENERIC_TIMEZONE: "America/Sao_Paulo"
  DB_TYPE: "postgresdb"
  DB_POSTGRESDB_DATABASE: "n8n_queue"
  DB_POSTGRESDB_HOST: "postgres-service"
  DB_POSTGRESDB_PORT: "5432"
  DB_POSTGRESDB_USER: "n8n"
  N8N_PORT: "5678"
  N8N_HOST: "n8n.editor.mvpos.app.br"
  N8N_EDITOR_BASE_URL: "https://editor.mvpos.app.br/"
  N8N_PROTOCOL: "https"
  WEBHOOK_URL: "https://webhook.mvpos.app.br/"
  N8N_ENDPOINT_WEBHOOK: "webhook"
  EXECUTIONS_MODE: "queue"
  QUEUE_BULL_REDIS_HOST: "redis-service"
  QUEUE_BULL_REDIS_PORT: "6379"
  QUEUE_BULL_REDIS_DB: "2"
  EXECUTIONS_TIMEOUT: "3600"
  EXECUTIONS_TIMEOUT_MAX: "7200"
  N8N_VERSION_NOTIFICATIONS_ENABLED: "true"
  N8N_PUBLIC_API_SWAGGERUI_DISABLED: "false"
  N8N_TEMPLATES_ENABLED: "true"
  N8N_ONBOARDING_FLOW_DISABLED: "true"
  N8N_WORKFLOW_TAGS_DISABLED: "false"
  N8N_HIDE_USAGE_PAGE: "true"
  EXECUTIONS_DATA_PRUNE: "true"
  EXECUTIONS_DATA_MAX_AGE: "336"
  EXECUTIONS_DATA_PRUNE_HARD_DELETE_INTERVAL: "15"
  EXECUTIONS_DATA_PRUNE_SOFT_DELETE_INTERVAL: "60"
  EXECUTIONS_DATA_PRUNE_MAX_COUNT: "10000"
  EXECUTIONS_DATA_SAVE_ON_ERROR: "all"
  EXECUTIONS_DATA_SAVE_ON_SUCCESS: "all"
  EXECUTIONS_DATA_SAVE_ON_PROGRESS: "true"
  EXECUTIONS_DATA_SAVE_MANUAL_EXECUTIONS: "true"
  NODE_FUNCTION_ALLOW_BUILTIN: "*"
  NODE_FUNCTION_ALLOW_EXTERNAL: "moment,lodash"
  N8N_COMMUNITY_PACKAGES_ENABLED: "true"
  N8N_REINSTALL_MISSING_PACKAGES: "true"
  N8N_AI_ENABLED: "false"
  N8N_AI_PROVIDER: "openai"
  N8N_AI_OPENAI_API_KEY: ""
  N8N_METRICS: true
  N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: true
  N8N_RUNNERS_ENABLED: true